// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

//go:generate mockgen -destination ./user_mock.go -package userclient -source $GOFILE

package userclient

import (
	"context"

	"go-zero-demo/mall/user/rpc/user"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	IdRequest        = user.IdRequest
	UserResponse     = user.UserResponse
	NameRequest      = user.NameRequest
	UserNameResponse = user.UserNameResponse

	User interface {
		GetUser(ctx context.Context, in *IdRequest) (*UserResponse, error)
		GetId(ctx context.Context, in *NameRequest) (*UserNameResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUser(ctx context.Context, in *IdRequest) (*UserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in)
}

func (m *defaultUser) GetId(ctx context.Context, in *NameRequest) (*UserNameResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetId(ctx, in)
}
